# Generated by Django 4.2.4 on 2023-08-31 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=256)),
                ('name_ru', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=256)),
                ('name_ru', models.CharField(max_length=256)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.province')),
            ],
        ),
    ]
