# Generated by Django 4.2.4 on 2023-08-31 05:18

from django.db import migrations

def populate_data(apps, schema_editor):
    Province = apps.get_model('data', 'Province')
    District = apps.get_model('data', 'District')

    # Create Fargona province
    fargona = Province.objects.create(name_uz='Farg\'ona', name_ru='Фарғона')

    # Create districts for Fargona province
    fargona_districts = [
        {'name_uz': 'Beshariq', 'name_ru': 'Бешариқ'},
        {'name_uz': 'Dangara', 'name_ru': 'Данғара'},
        {'name_uz': 'Furqat', 'name_ru': 'Фурқат'},
        {'name_uz': 'Farg\'ona shahri', 'name_ru': 'Фарғона шаҳри'},
        # Add more districts as needed
    ]
    for district in fargona_districts:
        District.objects.create(province=fargona, **district)

    # Create Tashkent province
    tashkent = Province.objects.create(name_uz='Toshkent', name_ru='Тошкент')

    # Create districts for Tashkent province
    tashkent_districts = [
        {'name_uz': 'Bektemir', 'name_ru': 'Бектемир'},
        {'name_uz': 'Mirobod', 'name_ru': 'Миробод'},
        {'name_uz': 'Sergeli', 'name_ru': 'Сергели'},
        {'name_uz': 'Yunusobod', 'name_ru': 'Юнусобод'},
        # Add more districts as needed
    ]
    for district in tashkent_districts:
        District.objects.create(province=tashkent, **district)


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_data),
    ]