# Generated by Django 4.2.4 on 2023-08-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_orders_from_to_alter_orders_where'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
