USER_STEP = {
    'DEFAULT': 0,
    'ENTER_FIRST_NAME': 1,
    'CHOOSE_LOCATION': 2,
    'SELECT_DISTRICT': 3,
    'NUMBER_OF_PASSANGERS': 4,
    'THANK_YOU_MESSAGE': 5,
}

BUTTONS = {
    'BACK': 'Orqaga qaytish'
}

CHANNEL_ID = '-1001718993048'
